eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    config:
      override-system-properties: false
management:
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans # due to spring default url, no need to specify
  tracing:
    sampling:
      probability: 1.0