#spring:
#  data:
#    mongodb:
#      username: lucky
#      password: 1234
#      host: localhost
#      port: 27017
#      database: customer
#      authentication-database: admin
spring:
  data:
    mongodb:
      uri: mongodb://lucky:1234@localhost:27017/customer?authSource=admin

server:
  port: 8090